{{ $common := .Values.common }}
{{- if $common.infisical.commonSecret.enabled }}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "citadel-common.fullname" $ }}-common-env-vars
  annotations:
    "helm.sh/hook": {{ default "pre-install,pre-upgrade" $common.infisical.helmHook }}
    "helm.sh/hook-weight": {{ default "-15" $common.infisical.helmHookWeight | quote }}
spec:
  hostAPI: {{ $common.infisical.url }}
  resyncInterval: {{ $common.infisical.resyncInterval }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ $common.infisical.commonSecret.projectSlug }}
        envSlug: {{ $common.environment }}
        secretsPath: {{ $common.infisical.commonSecret.secretsPath }}
      credentialsRef:
        secretName: {{ default "client-infisical-secrets" $common.infisical.commonSecret.secretName }}
        secretNamespace: {{ $.Release.Namespace }}
  managedKubeSecretReferences:
    - secretName: {{ include "citadel-common.fullname" $ }}-common-env-vars
      secretNamespace: {{ $.Release.Namespace }}
      creationPolicy: "Orphan"
{{- end }}

{{- range $app := .Values.applications }}
{{- if and $app.infisical $app.infisical.enabled }}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "citadel-common.fullname" $ }}-{{ .name }}-env-vars
  annotations:
    "helm.sh/hook": {{ default "pre-install,pre-upgrade" $common.infisical.helmHook }}
    "helm.sh/hook-weight": {{ default "-15" $common.infisical.helmHookWeight | quote }}
spec:
  hostAPI: {{ $common.infisical.url }}
  resyncInterval: {{ $common.infisical.resyncInterval }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ $app.infisical.projectSlug }}
        envSlug: {{ $common.environment }}
        secretsPath: {{ $app.infisical.secretsPath }}
      credentialsRef:
        secretName: {{ default "client-infisical-secrets" $app.infisical.secretName }}
        secretNamespace: {{ $.Release.Namespace }}
  managedKubeSecretReferences:
    - secretName: {{ include "citadel-common.fullname" $ }}-{{ .name }}-env-vars
      secretNamespace: {{ $.Release.Namespace }}
      creationPolicy: "Orphan"
{{- end }}
{{- end }}
