{{ $common := .Values.common }}
{{- range $job := .Values.jobs }}
{{- if $job.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "citadel-common.fullname" $ }}-job-{{ .name }}
  labels:
    {{- include "citadel-common.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ default "pre-install,post-upgrade" $job.helmHook }}
    "helm.sh/hook-delete-policy": {{ default "before-hook-creation,hook-succeeded" $job.helmHookDeletePolicy }}
    "helm.sh/hook-weight": {{ $job.hookWeight | default "10" | quote }}
spec:
  {{- with $job.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with $job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "citadel-common.labels" $ | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "citadel-common.serviceAccountName" $ }}
      {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-{{ .name }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ if or $common.env .env  }}
          env:
            {{- with $common.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          image: "{{ if $job.image }}{{ default $common.image.repository $job.image.repository }}{{ else }}{{ $common.image.repository }}{{ end }}:{{ if $job.image }}{{ default $common.image.tag $job.image.tag }}{{ else }}{{ $common.image.tag }}{{ end }}"
          imagePullPolicy: {{ if $job.image }}{{ default $common.image.pullPolicy $job.image.pullPolicy }}{{ else }}{{ $common.image.pullPolicy }}{{ end }}
          {{- with .command }}
          command: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.args }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $common.infisical.enabled }}
          envFrom:
            {{- if $common.infisical.enabled }}
            - secretRef:
                name: {{ include "citadel-common.fullname" $ }}-common-env-vars
            {{- end }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $common.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $common.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
