{{ $common := .Values.common }}
{{- if $common.sharedPVCs }}
{{- range $common.sharedPVCs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "citadel-common.fullname" $ }}-{{ .name }}
  labels:
    {{- include "citadel-common.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "5"
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
