{{- range .Values.applications }}
{{- if and .service .serviceMonitor (and .serviceMonitor .serviceMonitor.enabled) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "citadel-common.fullname" $ }}-{{ .name }}
  labels:
    {{- include "citadel-common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
    {{- with .serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "citadel-common.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
  endpoints:
    - port: {{ default (printf "http-%s" .name) .serviceMonitor.portName }}
      path: {{ .serviceMonitor.path }}
      interval: {{ .serviceMonitor.interval }}
      scrapeTimeout: {{ .serviceMonitor.scrapeTimeout }}
      {{- with .serviceMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .serviceMonitor.honorTimestamps }}
      honorTimestamps: {{ . }}
      {{- end }}
      {{- with .serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .serviceMonitor.basicAuth }}
      basicAuth:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .serviceMonitor.bearerTokenSecret }}
      bearerTokenSecret:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with .serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
