name: Update Helm Repository

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/update-repo.yaml'

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package charts
        run: |
          mkdir -p packages
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging $chart"
              helm package "$chart" -d packages/
            fi
          done

      - name: Update index
        run: |
          helm repo index . --url https://ilyario.github.io/ah-helm-charts --merge index.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.yaml
          git add packages/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Helm repository index"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
